INSERT INTO KUNDE (KUNDENNUMMER, NAME, EMAIL)
VALUES (1, 'Max Mustermann', 'max@example.com');

INSERT INTO PRODUKT (PRODUKTNUMMER, NAME, PREIS, BESTAND, BESCHREIBUNG, KATEGORIE, LIEFERZEIT)
VALUES (1, 'MacBook Pro', 2499.99, 2, 'Apple Laptop', 'Laptops', '2-3 Tage');